            - назва: середовище налаштування Node.js
  використовує: actions/setup-node@v4.1.0
  з:
    # Встановити завжди автентифікацію в npmrc.
    always-auth: # необов’язковий, за умовчанням false
    # Специфікація версії для використання. Приклади: 12.x, 10.15.1, >=10.15.0.
    node-version: # необов'язковий
    # Файл, що містить специфікацію версії для використання. Приклади: package.json, .nvmrc, .node-version, .tool-versions.
    node-version-file: # необов'язковий
    # Цільова архітектура для Node для використання. Приклади: x86, x64. Буде використовувати системну архітектуру за замовчуванням.
    архітектура: # необов'язкова
    # Встановіть цей параметр, якщо ви хочете, щоб дія перевіряла останню доступну версію, яка задовольняє специфікації версії.
    перевірка останнього: # необов'язковий
    # Додатковий реєстр для налаштування авторизації. Буде встановлено реєстр у файлі .npmrc і .yarnrc на рівні проекту та налаштовано авторизацію для читання з env.NODE_AUTH_TOKEN.
    URL-адреса реєстру: # необов'язковий
    # Додаткова область для автентифікації щодо реєстрів із обмеженою областю. Повернеться до власника сховища під час використання реєстру пакетів GitHub (https://npm.pkg.github.com/).
    область: # необов'язковий
    # Використовується для отримання розповсюджень вузлів із версій вузлів. Оскільки існує значення за замовчуванням, користувач зазвичай не вказує його. Під час виконання цієї дії на github.com достатньо значення за умовчанням. Під час роботи на GHES ви можете передати особистий маркер доступу для github.com, якщо у вас є обмеження швидкості.
    маркер: # необов’язковий, за умовчанням ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Використовується для визначення менеджера пакетів для кешування в каталозі за замовчуванням. Підтримувані значення: npm, yarn, pnpm.
    кеш: # необов'язковий
    # Використовується для вказівки шляху до файлу залежностей: package-lock.json, yarn.lock тощо. Підтримує символи підстановки або список імен файлів для кешування кількох залежностей.
    шлях залежностей кешу: # необов'язковий
          
